version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: elasticsearch
    privileged: true
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch 
      - bootstrap.memory_lock=false
      - gateway.auto_import_dangling_indices=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: kibana:7.11.1
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - "kibana:/usr/share/kibana/config"
    ports:
      - 5601:5601
    networks:
      - elastic
  
  metricbeat:
    image: elastic/metricbeat:7.11.1
    container_name: metricbeat
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=elasticsearch:9200
    volumes:
      - "metricbeat:/usr/share/metricbeat/"
    networks:
      - elastic

volumes:
  elasticsearch:
    driver: local
  kibana:
    driver: local
  metricbeat:
    driver: local

networks:
  elastic:
    driver: bridge

