version: '3.3'
services:
  es01:
    image: elasticsearch:7.11.1
    container_name: es01
    privileged: true
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01 
      - bootstrap.memory_lock=false
      - gateway.auto_import_dangling_indices=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge

